services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - 2345:5432
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - back-end/.env #config POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env #configurar DATABASE_URL  

volumes:
  pg: