services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    ports:
      - 2345:5432
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - back-end/.env #config POSTGRES_USER, POSTGRES_PASSWORD e POSTGRES_DB
    
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env #configurar DATABASE_URL  

  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
    env_file:
      - front-end/.env

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - react_app

volumes:
  pg:
  build_react: